### ISSUE TITLE
Qué tan completa está esta librería?

### ISSUE THREAD

**Issue by javorosas** [open-pay/openpay-node#1]
Hola. quisiera saber que tanto de las funcionalidades de openpay cubre su implementación de Node, y si está preparada para producción.

Viendo el github de la de ruby me doy cuenta que la otra tiene mucha más funcionalidad. Lo que me interesa concretamente es poder obtener todos los cargos que le he hecho a un cliente en específico.

Gracias.

**Comment by darkaz** [comment]
Hola Javo,

La librería se encuentra aún 99% podríamos decir. Para hacer lo que comentas usa el método:
openpay.customers.charges.list

Saludos
