### ISSUE TITLE
Cómo puedo hacer que una suscripción cambie de plan?

### ISSUE THREAD

**Issue by javorosas** [open-pay/openpay-node#2]
Hola. Necesito soportar que el cliente pueda actualizar su plan en cualquier momento. ¿Es posible actualizar una suscripción para cambiar de plan? No pude encontrar referencia a ello en la documentación.

También, ¿cómo me recomiendan lidiar con el cobro en ese caso? Me comentan que no manejan el cobro proporcional. ¿Qué estrategia recomiendan seguir en el caso de que alguien haga un upgrade?

Gracias

**Comment by AMEnterprises** [comment]
Hola, encontraste alguna forma de hacer esto? Estoy atorado en esto también.
Gracias!

**Comment by javorosas** [comment]
No. Me cambié a [Stripe](https://stripe.com/). Están en beta cerrada pero con un tweet a Stripe Mexico consigues la invitación. Es extremadamente sencillo de implementar, créeme. Yo me ahorré horas y horas de haber gastado intentando lidiar con OpenPay.

**Comment by AMEnterprises** [comment]
Igual llevo ya un tiempo buscando que me den acceso a la beta privada pero sin éxito. Pero igual intentare con el tweet que me dices, muchas gracias!!

**Comment by marcelinols** [comment]
Yo lo pude lograr haciendo estos pasos.
-Crear subscripcion
// crea el customer.     
$customer = $openpay->customers->add($customerData);
//crea la tarjeta.        
$card = $customer->cards->add($cardData);  
//crea la subscripcion
$subscriptionDataRequest = array(
    'trial_end_date' => date('Y-m-d', strtotime(date("Y-m-d"). ' + 30 days')), 
    'plan_id' => $planId,
    'source_id' => $card->id);
$subscription = $customer->subscriptions->add($subscriptionDataRequest);
  
- actualizar subscripcion
//consultamos el id de la tarjeta de la susscripcion y eliminamos esa subscripcion 
$customer = $openpay->customers->get($id_customer);
$subscription = $customer->subscriptions->get($_POST['subscription']);
$id_card = $subscription->card->id;
$subscription->delete(); 
//creamos la nueva subscripcion con la misma tarjeta 
$subscriptionDataRequest = array(
        'trial_end_date' => date('Y-m-d'), 
        'plan_id' => $_POST['id_plan'],
        'source_id' => $id_card
    );

$customer = $openpay->customers->get($id_customer);
$subscription = $customer->subscriptions->add($subscriptionDataRequest);
