### ISSUE TITLE
'no auth mechanism defined usando' Heroku

### ISSUE THREAD

**Issue by joscor34** [open-pay/openpay-node#21]
Estoy tratando de hacer el cobro a una tarjeta utilizando el token, cuando lo pruebo en localhost el pago se realiza de manera correcta, sin embargo cuando subo mi API a un servidor en Heroku, al momento de ejecutar el método, me regresa el siguiente error "no auth mechanism defined"

**Comment by Darkboy5120** [comment]
por si alguien mas esta sufriendo con esto, en mi caso era tema de mi archivo .env, no se estaban cargando las variables, y estaba pasando la llave publica y privada como undefined al la instancia de openpay, instale y configure el paquete dotenv y todo listo
