### ISSUE TITLE
No permite borrar un usuario si no se borran primero sus suscripciones

### ISSUE THREAD

**Issue by javorosas** [open-pay/openpay-node#3]
En la [documentación sobre eliminar cliente](http://www.openpay.mx/docs/api/#eliminar-un-cliente) dice:

>Elimina un cliente permanentemente. Se cancelarán las suscripciones que tenga. Openpay mantiene los registros de las operaciones.

Sin embargo, al hacer la llamada para eliminar un cliente con suscripciones activas, el servidor me regresa un objeto de error:

	{
		category: "request",
		description: "The customer has subscriptions that need to be cancelled before deletion",
		error_code: 1013,
		http_code: 412,
		request_id: "b3fd8974-7fb5-4c59-8739-2c6b354f9102"
	}

Por lo que dice la documentación, yo esperaría que se cancelen automáticamente sus suscripciones.

¿O cuál debería de ser el comportamiento esperado?

Gracias.

**Comment by darkaz** [comment]
Hola @javorosas 

El comportamiento debe ser como se describe en la documentación. Vamos a revisarlo.

Saludos
