### ISSUE TITLE
 'The card charge is on a final status'

### ISSUE THREAD

**Issue by lorenzolopez928** [open-pay/openpay-node#5]
Buenas noches, tengo un servidor montado en node.js que a la hora de cobrar los pagos primero se crea el cargo de la siguiente forma
var chargeRequest = {
            method: 'card',
            source_id: source_id,
            amount: amount,
            description: description,
            device_session_id: device_session_id,
            capture: capture,
            currency: 'MXN',
            customer: {
                name: customer_name,
                last_name: customer_last_name,
                phone_number: customer_phone_number,
                email: customer_email
            }
        };
        openpayApi.charges.create(chargeRequest, (error, resp)=>{
            if(error){
              return  reject(error);
            }
            return resolve(resp);
        });

y luego se confirma el mismo variando el monto y el mensaje de la siguiente manera

var captureRequest = {
      amount: amount
    }
    openpayApi.charges.capture(transactionId, captureRequest, (err, resp)=>{
        if(err) return reject(err);
        resolve(resp);
    });

Sin embargo existen situaciones en los que openpay devuelve lo siguiente y no sabemos que puede estar pasando

{ category: 'request',
  description: 'The card charge is on a final status',
  http_code: 422,
  error_code: 1003,
  request_id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' }

**Comment by marcosAlvarado** [comment]
Hola lorenzolopez928!

Podrías darnos tu request_id para revisar que es lo que nos esta llegando?

Que tengas buenas noches!

**Comment by reneponce** [comment]
Buenas tardes tengo el mismo problema al momento de hacer un pre cargo todo funciona correctamente pero al momento de confirmar el cargo me regresa lo siguiente.

{
    "category": "request",
    "description": "The card charge is on a final status",
    "http_code": 422,
    "error_code": 1003,
    "request_id": "xxxxxxxxxxxxxxxx"
}

**Comment by jemy-dasm-openpay** [comment]
Este error ocurre al intentar confirmar dos veces la misma transacción.

**Comment by scooller** [comment]
Tengo el mismo problema pero al realizar la comprobación con re dirección
