### ISSUE TITLE
Como obtener device_session_id

### ISSUE THREAD

**Issue by LuisRodriguezLD** [open-pay/openpay-node#6]
Segun su [documentacion](https://www.openpay.mx/docs/api/#con-id-de-tarjeta-o-token), para poder hacer un pago necesito el `device_session_id`.

Como puedo obtenerlo usando NodeJS?
Solo encontre la funcion en [Javascript normal](https://github.com/open-pay/openpay-js#fraud-detection-using-device-data) pero *necesito* hacerlo por aqui

**Comment by oswaldopenpay** [comment]
Buenas tardes

El device_session_id debe ser generado desde el formulario de compra utilizando java script como se describe en la documentación https://openpay.mx/docs/card-charge.html

**Comment by LuisRodriguezLD** [comment]
Oh, al parecer lo pone automáticamente. Sugiero crear una función para regresar solamente ese id
