### ISSUE TITLE
Unable to resolve module `http`from `project-name/node_modules/openpay/node_modules/request/request.js`

### ISSUE THREAD

**Issue by luisfher20** [open-pay/openpay-node#8]
```Unable to resolve module `http`from `project-name/node_modules/openpay/node_modules/request/request.js`: Module `http`does not exist in the Haste module map.```

Is there a way to solve this error, I just installed openpay-node for a react native project and as soon as I require the library I get that error

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there have been many updates since it was opened.

Hopefully you're not having this issue anymore but if there are problems still happening please let us know and we'll open this issue again.

Cheers!
